User.create(first_name: "Kiran", last_name: "C", email: "phanendar@gmail.com", password: "1234")
User.create(first_name: "Trevor", last_name: "Nelson", email: "trevor@gmail.com", password: "1234")
User.create(first_name: "Natalia", last_name: "Bryzhatenko", email: "natalia@gmail.com", password: "1001")
Task.create(title: "Hang with Chris", completed: false, day: "Monday", user_id: 1, category_id: 1)
Task.create(title: "Hang with Ivan", completed: false, day: "Tuesday", user_id: 1, category_id: 2)
Task.create(title: "Hang with Pluto", completed: false, day: "Wednesday", user_id: 1, category_id: 1)
Task.create(title: "Hang with Trevor", completed: false, day: "Thursday", user_id: 1, category_id: 2)
Task.create(title: "Hang with Tina", completed: false, day: "Friday", user_id: 1, category_id: 1)
Task.create(title: "Smoke all day", completed: false, day: "Monday", user_id: 1, category_id: 1)
Task.create(title: "Drink all day", completed: false, day: "Monday", user_id: 1, category_id: 2)
Task.create(title: "Hang with Melissa", completed: false, day: "Tuesday", user_id: 1, category_id: 6)
Task.create(title: "Hang with Jessica", completed: false, day: "Monday", user_id: 1, category_id: 3)
Task.create(title: "Hang with Aubrey", completed: false, day: "Tuesday", user_id: 1, category_id: 2)
Task.create(title: "Hang with Martin", completed: false, day: "Monday", user_id: 1, category_id: 3)
Task.create(title: "Hang with Chris", completed: false, day: "Wednesday", user_id: 1, category_id: 2)
Task.create(title: "Hang with James", completed: false, day: "Wednesday", user_id: 1, category_id: 5)
Task.create(title: "Hang with Kyle", completed: false, day: "Friday", user_id: 1, category_id: 4)
Task.create(title: "Hang with Ram", completed: false, day: "Friday", user_id: 1, category_id: 1)
Category.create(title: "relationships")
Category.create(title: "learning")
Category.create(title: "health")
Category.create(title: "professional")
Category.create(title: "spiritual")
Category.create(title: "relaxation")
Subtask.create(title: "some subtask", task_id: 2)
Subtask.create(title: "some other subtask", task_id: 2)
Subtask.create(title: "another subtask", task_id: 2)
Subtask.create(title: "oh look, a subtask", task_id: 7)
Subtask.create(title: "subtask!", task_id: 10)
Subtask.create(title: "a subtask", task_id: 10)
Subtask.create(title: "this subtask", task_id: 9)
Subtask.create(title: "maybe a subtask", task_id: 9)
Subtask.create(title: "subtaskkkkkk", task_id: 5)
Subtask.create(title: "subtask?", task_id: 6)

