User.create(first_name: "Kiran", last_name: "C", email: "phanendar@gmail.com", password: "1234")
User.create(first_name: "Trevor", last_name: "Nelson", email: "trevor@gmail.com", password: "1234")
Category.create(title: "recreation")
User.create(first_name: "Natalia", last_name: "Bryzhatenko", email: "natalia@gmail.com", password: "1001")
Category.create(title: "family/relationships")
Category.create(title: "learning")
Category.create(title: "health")
