User.create(first_name: "Kiran", last_name: "C", email: "phanendar@gmail.com", password: "1234")
User.create(first_name: "Trevor", last_name: "Nelson", email: "trevor@gmail.com", password: "1234")
Category.create(title: "recreation")
User.create(first_name: "Natalia", last_name: "Bryzhatenko", email: "natalia@gmail.com", password: "1001")
Task.create(title: "Hang with Chris", completed: false, day: "Monday", user_id: 1, category_id: 1)
Task.create(title: "Hang with Ivan", completed: false, day: "Tuesday", user_id: 1, category_id: 2)
Task.create(title: "Hang with Pluto", completed: false, day: "Wednesday", user_id: 1, category_id: 1)
Task.create(title: "Hang with Trevor", completed: false, day: "Thursday", user_id: 1, category_id: 2)
Task.create(title: "Hang with Tina", completed: false, day: "Friday", user_id: 1, category_id: 1)
Task.create(title: "Smoke all day", completed: false, day: "Monday", user_id: 1, category_id: 1)
Task.create(title: "Drink all day", completed: false, day: "Monday", user_id: 1, category_id: 2)
Task.create(title: "Hang with Melissa", completed: false, day: "Tuesday", user_id: 1, category_id: 1)
Task.create(title: "Hang with Jessica", completed: false, day: "Monday", user_id: 1, category_id: 3)
Task.create(title: "Hang with Aubrey", completed: false, day: "Tuesday", user_id: 1, category_id: 2)
Task.create(title: "Hang with Martin", completed: false, day: "Monday", user_id: 1, category_id: 3)
Task.create(title: "Hang with Chris", completed: false, day: "Wednesday", user_id: 1, category_id: 2)
Task.create(title: "Hang with James", completed: false, day: "Wednesday", user_id: 1, category_id: 2)
Task.create(title: "Hang with Kyle", completed: false, day: "Friday", user_id: 1, category_id: 1)
Task.create(title: "Hang with Ram", completed: false, day: "Friday", user_id: 1, category_id: 1)
Category.create(title: "family/relationships")
Category.create(title: "learning")
Category.create(title: "health")

